### ISSUE TITLE
homelab - 3. 基础设施建设 - 网关

### ISSUE THREAD

**Issue by he-sb** [he-sb/tech#50]
1. 主网关（拨号，路由，分流）
2. 旁路网关（提供翻墙服务）
3. 反向代理（Traefik）
    - 对内网提供的服务。需要一个统一的入口
    - 自动服务发现

**Comment by he-sb** [comment]
*参考链接：*

1. [ROS等路由器MTU值取值及修改详解-山隈的博客](http://blog.leanote.com/post/qyj229/ROS%E7%AD%89%E8%B7%AF%E7%94%B1%E5%99%A8MTU%E5%80%BC%E5%8F%96%E5%80%BC%E5%8F%8A%E4%BF%AE%E6%94%B9%E8%AF%A6%E8%A7%A3)
2. [谈一谈1G瓶颈的原理和影响-路由器交流](https://www.acwifi.net/19509.html)

**Comment by he-sb** [comment]
## 旁路网关

[使用 clash 搭建透明网关实现旁路科学上网自由 - akiyaの博客](https://little-star.love/posts/5d083060/)

[Linux系统结合clash做旁路网关/透明代理 - 长风记录](https://cff.pw/2021/11/17/linux-clash-gateway/)

**Comment by he-sb** [comment]
## Traefik

[新手入门 - Træfɪk中国](https://docs.traefik.cn/)

[Traefik](https://www.qikqiak.com/traefik-book/)

[Traefik-v2.x快速入门 - 腾讯云开发者社区-腾讯云](https://cloud.tencent.com/developer/article/1615712)

[Archive of Andrew's Blog](https://blog.abowden.net/archive)

[Ultimate Traefik Docker Compose Guide [2022] with LetsEncrypt | SHB](https://www.smarthomebeginner.com/traefik-docker-compose-guide-2022/) 参考【Security_Headers_as_Middlewares_File】小节配置 headers 信息

[Traefik 另类的服务暴露方式 - bleem](https://mritd.com/2018/05/24/kubernetes-traefik-service-exposure/)

[Traefik 2 监控系统之Grafana Prometheus Promtail Loki完美结合 - 简书](https://www.jianshu.com/p/68955d911fa4)

[HTTP to HTTPS redirects with Traefik | Jens Knipper](https://jensknipper.de/blog/traefik-http-to-https-redirect/)

[#Traefik 配置http自动跳转到https](https://xmanyou.com/traefik-redirect-http-request-to-https-on-same-entrypoint/)

---

traefik 定义路由时指定的 Host 字段必须用反引号包裹，避免域名被错误的转义（go 语言的特性，参考 https://www.smarthomebeginner.com/traefik-docker-compose-guide-2022/ ）

---

```bash
docker network create traefik
```

docker-compose.yml
<details>

```yml
version: '3'

services:

  traefik:
    container_name: traefik
    image: traefik:v2.9.5
    restart: always
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - '8080:8080'
    network_mode: host
    command:
      - '--global.sendanonymoususage=false'
      - '--global.checknewversion=false'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--api=true'
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--api.debug=false'
      - '--ping=true'
      - '--log.level=warn'
      - '--log.format=common'
      - '--accesslog=false'
      # 向 Prometheus 暴露监控指标
      # https://doc.traefik.io/traefik/observability/metrics/prometheus/
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.buckets=0.1,0.3,1.2,5.0'
      - '--metrics.prometheus.entryPoint=http'
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.swarmMode=false'
      - '--providers.docker.useBindPortIP=false'
      - '--providers.docker.network=traefik'
      - '--providers.file=true'
      - '--providers.file.watch=true'
      - '--providers.file.directory=/etc/traefik/config'
      - '--providers.file.debugloggeneratedtemplate=true'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/:/etc/traefik/config/:ro
      - ./ssl/:/data/ssl/:ro
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy off localhost:8080/ping || exit 1']
      interval: 3s
      retries: 12
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
```

</details>

config/traefik.yml
<details>

```yml
http:
  routers:
    traefik-default:
      entrypoints: 'http'
      rule: 'Host(`traefik.he-sb.home`)'
      service: 'dashboard@internal'

    traefik-dashboard:
      entrypoints: 'http'
      rule: 'Host(`traefik.he-sb.home`) && PathPrefix(`/`)'
      service: 'dashboard@internal'

    traefik-api:
      entrypoints: 'http'
      rule: 'Host(`traefik.he-sb.home`) && PathPrefix(`/api`)' 
      service: 'api@internal'

    traefik-ping:
      entrypoints: 'http'
      rule: 'Host(`traefik.he-sb.home`) && PathPrefix(`/ping`)'
      service: 'ping@internal'
```

</details>
