### ISSUE TITLE
homelab - 5. 上层建筑施工

### ISSUE THREAD

**Issue by he-sb** [he-sb/tech#51]
## 导航页（目前在使用）

[docker-flare](https://github.com/soulteary/docker-flare)

---

备选

https://github.com/bastienwirtz/homer

**Comment by he-sb** [comment]
## filebrowser - 简易文件管理

[Docker 安装 File Browser | HE-SB-技术栈](https://tech.he-sb.top/posts/setup-filebrowser-in-docker/)

filebrowser/docker-compose.yml
<details>

## `filebrowser/docker-compose.yml`

```yml
version: '3'

services:
  filbrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: $DOCKER_UID_GID
    volumes:
      - /home/jokerh:/srv
      - /home/jokerh/filebrowser/database.db:/database.db
    restart: unless-stopped
    ports:
      - 8666:80
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
```

## `portainer-ce/docker-compose.yml`

```yaml
version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
    ports:
      - 8000:8000
      - 9443:9443
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'
```

</details>

自定义图标样式（默认为单色）

[Filebrowser Custom Ico... | The Homelab Wiki](https://thehomelab.wiki/books/other-guides/page/filebrowser-custom-icon-colors-how-to)
